[versions]
lombok = "1.18.42"

protobuf-plugin = "0.9.4"

springCloud = "3.2.12"
springAi = "1.1.2"
springBoot = "3.5.10"
springDoc = "2.8.14"

calcite = "1.41.0"
junit = "6.0.2"
mockito = "5.21.0"
assertj = "3.27.3"
protobuf = "4.33.5"
grpc = "1.79.0"
apacheCommons = "3.14.0"
apachePoi = "5.4.1"
apacheArrow = "17.0.0"
substrait = "0.60.0"
bootGRPC = "3.1.0.RELEASE"
jakartaServletApi = "6.1.0"
googleApiGrpc = "2.63.1"
jackson = "2.21.0"
guava = "33.3.1-jre"
okhttp = "5.3.2"
sqlline = "1.12.0"

micrometer = "1.16.0"

kotlin = "2.3.10"
logback = "1.5.28"
[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

spring-security-test = { module = "org.springframework.security:spring-security-test", version = "6.5.7" }

boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
boot-starter-security-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "springBoot" }
boot-starter-security-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server", version.ref = "springBoot" }
boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBoot" }
boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }

spring-cloud-function-grpc = { module = "org.springframework.cloud:spring-cloud-function-grpc", version.ref = "springCloud" }
spring-cloud-function-context = { module = "org.springframework.cloud:spring-cloud-function-context", version.ref = "springCloud" }
spring-cloud-function-adapter-azure = { module = "org.springframework.cloud:spring-cloud-function-adapter-azure", version.ref = "springCloud" }
spring-cloud-function-adapter-azure-web = { module = "org.springframework.cloud:spring-cloud-function-adapter-azure-web", version.ref = "springCloud" }
spring-cloud-starter-function-web = { module = "org.springframework.cloud:spring-cloud-starter-function-web", version.ref = "springCloud" }

spring-ai-client-chat = { module = "org.springframework.ai:spring-ai-client-chat", version.ref = "springAi" }
spring-ai-vector-store = { module = "org.springframework.ai:spring-ai-vector-store", version.ref = "springAi" }
spring-ai-starter-model-azureopenai = { module = "org.springframework.ai:spring-ai-starter-model-azure-openai", version.ref = "springAi" }
spring-ai-starter-model-openai = { module = "org.springframework.ai:spring-ai-starter-model-openai", version.ref = "springAi" }
spring-ai-starter-model-ollama = { module = "org.springframework.ai:spring-ai-starter-model-ollama", version.ref = "springAi" }
spring-ai-starter-mcp-server-starter = { module = "org.springframework.ai:spring-ai-mcp-server-spring-boot-starter", version.ref = "springAi" }
spring-ai-starter-mcp-server-webmvc = { module = "org.springframework.ai:spring-ai-starter-mcp-server-webmvc", version.ref = "springAi" }
spring-ai-starter-model-chat-memory-repository-jdbc = { module = "org.springframework.ai:spring-ai-starter-model-chat-memory-repository-jdbc", version.ref = "springAi" }

calcite-core = { module = "org.apache.calcite:calcite-core", version.ref = "calcite" }
calcite-server = { module = "org.apache.calcite:calcite-server", version.ref = "calcite" }
calcite-testkit = { module = "org.apache.calcite:calcite-testkit", version.ref = "calcite" }
calcite-file = { module = "org.apache.calcite:calcite-file", version.ref = "calcite" }
calcite-csv = { module = "org.apache.calcite:calcite-csv", version.ref = "calcite" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit" }
junit-bom = { module = "org.junit.jupiter:junit-bom", version.ref = "junit" }

slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
fusesource-jansi = { module = "org.fusesource.jansi:jansi", version = "2.4.2" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.4.0" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }

grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-api = { module = "io.grpc:grpc-api", version.ref = "grpc" }
grpc-core = { module = "io.grpc:grpc-core", version.ref = "grpc" }
grpc-testing = { module = "io.grpc:grpc-testing", version.ref = "grpc" }
grpc-inprocess = { module = "io.grpc:grpc-inprocess", version.ref = "grpc" }
grpc-census = { module = "io.grpc:grpc-census", version.ref = "grpc" }
grpc-all = { module = "io.grpc:grpc-all", version.ref = "grpc" }
grpc-context = { module = "io.grpc:grpc-context", version.ref = "grpc" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }

javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }

h2-database = { module = "com.h2database:h2", version = "2.4.240" }
hsqldb = { module = "org.hsqldb:hsqldb", version = "2.7.4" }

apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommons" }
apache-commons-codec = { module = "commons-codec:commons-codec", version = "1.21.0" }

substrait-core = { module = "io.substrait:core", version.ref = "substrait" }
substrait-isthmus = { module = "io.substrait:isthmus", version.ref = "substrait" }

bootGRPC-server = { module = "net.devh:grpc-server-spring-boot-starter", version.ref = "bootGRPC" }
bootGRPC-client = { module = "net.devh:grpc-client-spring-boot-starter", version.ref = "bootGRPC" }

jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakartaServletApi" }

googleapigrpc-proto-common-protos = { module = "com.google.api.grpc:proto-google-common-protos", version.ref = "googleApiGrpc" }

jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

guava = { module = "com.google.guava:guava", version.ref = "guava" }

okhttp-mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

opencensus-impl = { module = "io.opencensus:opencensus-impl", version = "0.31.1" }

pebble-templates = { module = "io.pebbletemplates:pebble", version = "4.1.1" }

sqlline = { module = "sqlline:sqlline", version.ref = "sqlline" }

drivers-postgressql = { module = "org.postgresql:postgresql", version = "42.7.9" }
drivers-sqllite = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }
drivers-mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version = "3.5.7" }
drivers-oracle = { module = "com.oracle:ojdbc14", version = "10.2.0.4.0" }
drivers-trino = { module = "io.trino:trino-jdbc", version = "479" }
drivers-duckdb = { module = "org.duckdb:duckdb_jdbc", version = "1.4.4.0" }
drivers-snowflake = { module = "net.snowflake:snowflake-jdbc", version = "4.0.0" }

apache-httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version = "5.6" }
apache-httpcore5 = { module = "org.apache.httpcomponents.core5:httpcore5", version = "5.4" }

univocity-parsers = { module = "com.univocity:univocity-parsers", version = "2.9.1" }
apache-avro = { module = "org.apache.avro:avro", version = "1.12.0" }
apache-parquet-avro = { module = "org.apache.parquet:parquet-avro", version = "1.15.0" }
apache-hadoop-common = { module = "org.apache.hadoop:hadoop-common", version = "3.4.1" }
apache-arrow-vector = { module = "org.apache.arrow:arrow-vector", version.ref = "apacheArrow" }
apache-arrow-memory-netty = { module = "org.apache.arrow:arrow-memory-netty", version.ref = "apacheArrow" }

apache-poi-ooxml-lite = { module = "org.apache.poi:poi-ooxml-lite", version.ref = "apachePoi" }
apache-poi-ooxml-full = { module = "org.apache.poi:poi-ooxml-full", version.ref = "apachePoi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "apachePoi" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "apachePoi" }

springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDoc" }
springdoc-openapi-starter-webflux-api = { module = "org.springdoc:springdoc-openapi-starter-webflux-api", version.ref = "springDoc" }

micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.3" }

json-path = { module = "com.jayway.jsonpath:json-path", version = "2.10.0" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version = "1.5.7" }

[bundles]
jackson = ["jackson-databind", "jackson-dataformat-yaml", "jackson-datatype-jsr310", "jackson-datatype-jdk8", "jackson-module-kotlin"]
logging = ["slf4j-api", "logback-core", "logback-classic", "fusesource-jansi"]
jdbc-pack = [
    "h2-database",
#    "hsqldb",
    "drivers-postgressql",
#    "drivers-sqllite",
    "drivers-mariadb",
#    "drivers-trino",
#    "drivers-duckdb",
#    "drivers-snowflake"
]

[plugins]
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
spring-boot-plugin = { id = "org.springframework.boot", version.ref = "springBoot" }
google-protobuf-plugin = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
kotlin = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-kapt = {id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}
kotlin-spring = {id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin"}
