include:  
  - local : /.gitlab/.common.yml

stages:  
  - init
  - test  

workflow:
  rules:
    - when : always


include:
  - local : /.gitlab/.common.yml
  - local : /clients/.gitlab/common.yml


##python 3.10
mill-py:test-3.10:  
  extends: .mill-py-test    
  variables:
    TEST_TYPE: "unit"
    PY_VER: "3.10"
  
##python 3.11
mill-py:test-3.11:  
  extends: .mill-py-test    
  variables:
    TEST_TYPE: "unit"
    PY_VER: "3.11"  

##python 3.12
mill-py:test-3.12:
  extends: .mill-py-test    
  variables:
    TEST_TYPE: "unit"
    PY_VER: "3.12"  

# jdbc-driver:test:
#   stage: test
#   extends: .gradle-job
#   script:
#     - echo $HOME
#     - cd ${CI_PROJECT_DIR}/clients
#     - ./gradlew --no-daemon --console plain test