core:build:
  stage: build
  extends: .gradle-job
  script:
    - echo $HOME    
    - ./gradlew --no-daemon --continue --console plain clean :core:test :core:compileTestIT
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - core/**/build/reports/tests/test/
      - core/**/build/reports/jacoco/test/
    reports:
      junit:
        - core/**/build/test-results/test/TEST-*.xml

core:integration:
  stage: integration
  extends:
    - .gradle-job
    - .integration-job
  script:
    - ./gradlew --no-daemon --continue --console plain clean :core:testIT