logging.level:
  org.springframework.security.web.csrf.CsrfFilter: debug

mill:
  security:
    enable: false
  backend:
    provider: jdbc
    connection:
      quoting: BACK_TICK
      caseSensitive: false
      unquotedCasing: UNCHANGED
    jdbc:
      url: "jdbc:trino://localhost:8082/tpch/sf1"
      driver: "io.trino.jdbc.TrinoDriver"
      user: "admin"
      password: ""
      target-schema: "trino"
  services:
    data-bot:
      enable: true
      prompt-file: file:../test/datasets/moneta/moneta.prompt
      api-key: ##
      model-name: gpt-4.1
