

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23litwNvltnAITfTG9
            client-secret: 085f77dc77b166181b363fd49cfbefca1eda703a
            scope: openid,profile,email
          azure:
            client-id: ${AZURE_TEST_CLIENT_ID}
            client-secret: ${AZURE_TEST_CLIENT_SECRET}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

mill:
  security:
    enable: true
    authentication:
      basic:
        enable: false
      oauth2-resource-server:
        enable: true
        jwt:
          jwk-set-uri: "https://login.microsoftonline.com/${AZURE_TEST_TENANT_ID}/discovery/v2.0/keys"