logging.level:
  org.springframework.security.web.csrf.CsrfFilter: debug

spring:
  ai:
 #   openai:
 #     api-key: #
 #     chat:
 #       model: gpt-4
    azure:
      openai:
        api-key: you_key_goes_here
        endpoint: https://your_endpoint.openai.net
        chat:
          options:
            deployment-name: gpt-4.1-deployment
    mcp:
      server:
        enabled: false
        name: moneta-agent
        transport:
          type: http
          endpoint: http://localhost:8080/mcp/task

mill:
  security:
    enable: false
  backend:
    provider: jdbc
    connection:
      quoting: BACK_TICK
      caseSensitive: false
      unquotedCasing: UNCHANGED
    jdbc:
      url: "jdbc:h2:mem:test;INIT=RUNSCRIPT FROM '../test/datasets/moneta/moneta.sql'"
      driver: "org.h2.Driver"
      username: "*"
      password: "*"
      target-schema: "MONETA"
  services:
    data-bot:
      enable: false
      prompt-file: file:../test/datasets/moneta/moneta.prompt
      model-name: gpt-4.1
