grpc:
  server:
    port: ${mill.data.services.grpc.port}
#    address: ${mill.data.services.grpc.address}

spring:
  application:
    name: ${mill.application.name}
  main:
    web-application-type: servlet

mill:
  application:
    name: mill-service
    hosts:
      externals:
        http:
          scheme: http
          host: localhost
          port: 8080
        grpc:
          scheme: grpc
          host: localhost
          port: 9090
  data:
    services:
      grpc:
        enable: true
        host:
          external: grpc
        port: 9090
      http:
        enable: true
        host:
          external: http
        port: 8080
## LEGACY subject to review
  security:
    enable: false
  metadata:
    relations: none
    annotations: none
  services:
    ai-nl2data:
      enable: false

