logging.level:
  root: INFO

mill:
  data:
    sql:
      dialect: calcite
    backend:
      type: flow
      flow:
        sources:
          - ./config/skymill-source.yaml
          - ./config/skymill-ref-source.yaml
  ai:
    nl2sql:
      enable: false
  security:
    enable: false
  metadata:
    relations: none
    annotations: none
  services:
    grinder:
      enable: true
    ai-nl2data:
      enable: false
    jet-http:
      enable: true
    grpc:
      enable: true
      port: 9090
    jet-grpc:
      enable: true
      port: 9090
    data-bot:
      enable: false
      prompt-file: file:../../test/datasets/skymill/skymill.prompt
      model-name: gpt-4.1
