{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mill-service.configMapName" . }}
  labels:
    {{- include "mill-service.labels" . | nindent 4 }}
data:
  application.yml: |
    {{- .Values.applicationConfig | nindent 4 }}
{{- end }}
