{{- if and .Values.secrets.create .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mill-service.fullname" . }}
  labels:
    {{- include "mill-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
